server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nc_movie
    username: postgres
    password: 3664
  jpa:
    hibernate:
      ddl-auto: create
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5555/r/authserver/user
